language: node_js
os:
  - windows
  - linux
  - osx

node_js:
  - "node"
  - 13
matrix:
## An ENOMEM error occurs with 10+ under Travis-CI for Windows.
## Disable until we can determine the cause.
  # include:
    # - node_js: 13.x
  # allow_failures:
  #   - node_js: tip
  exclude:
    - os: windows
      node_js: "node"
    - os: windows
      node_js: 13
# branches:
#   only:
#     - master
# git:
#   depth:
#     1
cache:
  npm: false
  # directories:
  #   - "$HOME/.npm"
before_install:
  - npm install
install:
  - npm ci
  # keep the npm cache around to speed up installs
# before_script:

# after_success:
#   - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.json